=== oppl/Comprehand/src-gen/twm/xmlSpec/metamodelSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- model -->
	<xs:element name="model">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="concept" />
				<xs:element ref="association" />
			</xs:choice>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="version" type="xs:string" />
			<xs:attribute name="author" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<!-- concept -->
	<xs:element name="concept">
		<xs:complexType>
			<xs:sequence>
				<!--  Realisation & Subrealisation -->
				<xs:element name="realisation" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="subrealisation" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="type" use="required">
										<xs:simpleType>
  											<xs:restriction base="xs:string">
   												<xs:minLength value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
  								<xs:restriction base="xs:string">
   									<xs:minLength value="1"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>					
				</xs:element>								
			</xs:sequence>		
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:ID">
						<xs:pattern value="[A-Z][a-zA-Z]*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>		
			<xs:attribute name="author" type="xs:string" />
			<xs:attribute name="owner" type="xs:string" />
		</xs:complexType>
		<!-- Realisations have to be unique within a concept -->
		<!--  
		<xs:key name="RealisationKey">
		<xs:selector xpath="realisation" /> 
		<xs:field xpath="@type" />
		</xs:key>
		-->
		<!--  Definition of a key for Realisation and Subrealisation types (union of types) -->
		<xs:key name="RealSubrealKey">
		<xs:selector xpath=".//subrealisation|.//realisation" /> 
		<xs:field xpath="@type" />
		</xs:key>	
	</xs:element>

	<!-- association -->
	<xs:element name="association">
		<xs:complexType>
			<xs:sequence>
				<!-- roles of an association -->			
				<xs:element name="role" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<!-- subroles of a role-->
						<xs:sequence>
							<xs:element name="subrole" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required" />
						<xs:attribute name="card" use="required">
							<xs:simpleType>
		  						<xs:restriction base="xs:string">
			  						<!-- Numbers 1-infinite -->
			    					<xs:pattern value="[1-9][0-9]*"/>
			    					<!-- + to represent 1 to * -->
			    					<xs:pattern value="[+]"/>
			    					<!-- range for numbers-->
			    					<xs:pattern value="[1-9][0-9]*[_][1-9][0-9]*"/>
			    					<!-- range from number to * -->
			    					<xs:pattern value="[1-9][0-9]*[_][*]"/>
		  						</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="subOccurOnce" type="xs:boolean"/>
					</xs:complexType>
				</xs:element>				
				<!-- valid role concept Combination of an association -->
				<xs:element name="valid-combination" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>						
							<xs:element name="role-ref" minOccurs="1" maxOccurs="unbounded"><!-- minOccurs = 1 fÃ¼r den default Fall, dann sollte aber card min 2 sein -->	
								<xs:complexType>
									<xs:sequence>
										<xs:element name="concept-ref" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:IDREF" use="required" />
											</xs:complexType>
										</xs:element>	
									</xs:sequence>								
									<xs:attribute name="name" type="xs:string" use="required" />
								</xs:complexType>
								<!-- concept-refs have to be unique within a role-ref -->
								<xs:key name="ConceptRefkey">
								<xs:selector xpath="concept-ref" /> 
								<xs:field xpath="@name" />
								</xs:key>
							</xs:element>																		
						</xs:sequence>					
					</xs:complexType>
					<!-- role-refs have to be unique within a valid combination -->
					<xs:key name="RoleRefkey">
					<xs:selector xpath="role-ref" /> 
					<xs:field xpath="@name" />
					</xs:key>
				</xs:element>
			</xs:sequence>
			<!-- attributes of an association -->
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:ID">
						<xs:pattern value="[A-Z][a-zA-Z]*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
		<!-- Definition of a key for role names of an association; name of role-Ref in valid-combination refers to role name -->
		<xs:key name="RoleKey">
		<xs:selector xpath="role" /> 
		<xs:field xpath="@name" />
		</xs:key>
		<xs:keyref name="validCombKeyRef" refer="RoleKey">
		<xs:selector xpath="valid-combination/role-ref" />
		<xs:field xpath="@name" />
		</xs:keyref>
		<!--  Definition of a key for Role and Subrole names (union of role and subrole names) within an association-->
		<xs:key name="RoleSubroleKey">
		<xs:selector xpath=".//subrole|.//role" /> 
		<xs:field xpath="@name" />
		</xs:key>	
	</xs:element>

</xs:schema>

=== oppl/Comprehand/src-gen/twm/xmlSpec/twm.xml
<?xml version="1.0" encoding="UTF-8"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="twm"
	version="1.0" author="MANE" xsi:noNamespaceSchemaLocation="metamodelSchema.xsd">
	<!-- based on paper: Towards Tangible Work Modeling - Stary,Oppl -->
	<concept name="Process">
		<realisation type="XAxis"/>
		<realisation type="YAxis"/>
		<realisation type="Rotation"/>
	</concept>
	
	<concept name="Role">
		<realisation type="XAxis"/>
		<realisation type="YAxis"/>
		<realisation type="Rotation"/>
	</concept>
	
	<concept name="Data">
		<realisation type="XAxis"/>
		<realisation type="YAxis"/>
		<realisation type="Rotation"/>
	</concept>
	
	<concept name="Goal">
		<realisation type="XAxis"/>
		<realisation type="YAxis"/>
		<realisation type="Rotation"/>
	</concept>

	<!-- Association Definitions between Basic Building Blocks-->
	<association name="Strictlybefore">
		<role name="before" card="1" />
		<role name="after" card="1" />
		<valid-combination>
			<role-ref name="before">
				<concept-ref name="Process" />
			</role-ref>
			<role-ref name="after">
				<concept-ref name="Process" />
			</role-ref>
		</valid-combination>
	</association>
	<association name="Creates">
		<role name="creates" card="1" />
		<role name="createdBy" card="1" />
		<valid-combination>
			<role-ref name="creates">
				<concept-ref name="Process" />
			</role-ref>
			<role-ref name="createdBy">
				<concept-ref name="Data" />
			</role-ref>
		</valid-combination>
	</association>
	<association name="IsInputFor">
		<role name="input" card="1" />
		<role name="processor" card="1" />
		<valid-combination>
			<role-ref name="processor">
				<concept-ref name="Process" />
			</role-ref>
			<role-ref name="input">
				<concept-ref name="Data" />
			</role-ref>
		</valid-combination>
	</association>
	<association name="Determines">
		<role name="determines" card="1" />
		<role name="determinedBy" card="1" />
		<valid-combination>
			<role-ref name="determines">
				<concept-ref name="Data" />
			</role-ref>
			<role-ref name="determinedBy">
				<concept-ref name="Data" />
			</role-ref>
		</valid-combination>
	</association>
	<association name="Interdependent">
		<role name="default" card="2_*" />
		<valid-combination>
			<role-ref name="default">
				<concept-ref name="Data" />
			</role-ref>
		</valid-combination>
	</association>
	<association name="Has">
		<role name="parent" card="1" />
		<role name="child" card="1" />
		<valid-combination>
			<role-ref name="parent">
				<concept-ref name="Process" />
			</role-ref>
			<role-ref name="child">
				<concept-ref name="Goal" />
			</role-ref>
		</valid-combination>
	</association>
	<association name="Responsible">
		<role name="responsible" card="1" />
		<role name="owned" card="1" />
		<valid-combination>
			<role-ref name="responsible">
				<concept-ref name="Role" />
			</role-ref>
			<role-ref name="owned">
				<concept-ref name="Process" />
			</role-ref>
		</valid-combination>
	</association>
	<association name="InvolesConsults">
		<role name="involves" card="1" />
		<role name="consults" card="1" />
		<valid-combination>
			<role-ref name="involves">
				<concept-ref name="Role" />
			</role-ref>
			<role-ref name="consults">
				<concept-ref name="Role" />
			</role-ref>
		</valid-combination>
	</association>

	<!-- Association Definitions between Basic Building Blocks and Artifacts-->
	
	<!-- RoleBBB container associations -->
	<association name="ContainedIn">
		<role name="container" card="1" />
		<role name="part" card="+" />
		<valid-combination>
			<role-ref name="container">
				<concept-ref name="Role" />
			</role-ref>
			<role-ref name="part">
				<concept-ref name="Role" />
			</role-ref>
		</valid-combination>
	</association>
	<association name="AssignmentOfRole">
		<role name="container" card="1" />
		<role name="assignedTo" card="+" />
		<valid-combination>
			<role-ref name="container">
				<concept-ref name="Role" />
			</role-ref>
			<role-ref name="assignedTo">
				<concept-ref name="Process" />
			</role-ref>
		</valid-combination>
	</association>
	<association name="DescriptionOfRole">
		<role name="container" card="1" />
		<role name="describes" card="+" />
		<valid-combination>
			<role-ref name="container">
				<concept-ref name="Role" />
			</role-ref>
			<role-ref name="describes">
				<concept-ref name="Data" />
			</role-ref>
		</valid-combination>
	</association>
	<association name="IntensionsOfRole">
		<role name="container" card="1" />
		<role name="part" card="+" />
		<valid-combination>
			<role-ref name="container">
				<concept-ref name="Role" />
			</role-ref>
			<role-ref name="part">
				<concept-ref name="Goal" />
			</role-ref>
		</valid-combination>
	</association>

	<!-- ProcessBBB container associations -->
	<association name="Supporter">
		<role name="supportedBy" card="1" />
		<role name="supports" card="+" />
		<valid-combination>
			<role-ref name="supportedBy">
				<concept-ref name="Process" />
			</role-ref>
			<role-ref name="supports">
				<concept-ref name="Role" />
			</role-ref>
		</valid-combination>
	</association>
	<association name="Detailing">
		<role name="ensemble" card="1" />
		<role name="detail" card="+" />
		<valid-combination>
			<role-ref name="ensemble">
				<concept-ref name="Process" />
			</role-ref>
			<role-ref name="detail">
				<concept-ref name="Process" />
			</role-ref>
		</valid-combination>
	</association>
	<association name="ProcessInstructions">
		<role name="process" card="1" />
		<role name="instruction" card="+" />
		<valid-combination>
			<role-ref name="process">
				<concept-ref name="Process" />
			</role-ref>
			<role-ref name="instruction">
				<concept-ref name="Data" />
			</role-ref>
		</valid-combination>
	</association>
	<association name="GoalOfProcess">
		<role name="process" card="1" />
		<role name="goal" card="+" />
		<valid-combination>
			<role-ref name="process">
				<concept-ref name="Process" />
			</role-ref>
			<role-ref name="goal">
				<concept-ref name="Goal" />
			</role-ref>
		</valid-combination>
	</association>

	<!-- DataBBB container associations -->
	<association name="OwnerResponsible">
		<role name="container" card="1" />
		<role name="responsible" card="+" />
		<valid-combination>
			<role-ref name="container">
				<concept-ref name="Data" />
			</role-ref>
			<role-ref name="responsible">
				<concept-ref name="Role" />
			</role-ref>
		</valid-combination>
	</association>
	<association name="LifecycleOfData">
		<role name="container" card="1" />
		<role name="part" card="+" />
		<valid-combination>
			<role-ref name="container">
				<concept-ref name="Data" />
			</role-ref>
			<role-ref name="part">
				<concept-ref name="Process" />
			</role-ref>
		</valid-combination>
	</association>
	<association name="ManipulationInstructions">
		<role name="container" card="1" />
		<role name="part" card="+" />
		<valid-combination>
			<role-ref name="container">
				<concept-ref name="Data" />
			</role-ref>
			<role-ref name="part">
				<concept-ref name="Data" />
			</role-ref>
		</valid-combination>
	</association>
	
</model>
